import { useState } from 'react'
import { motion } from 'framer-motion'
import { Copy, Check, TrendingUp } from 'lucide-react'
import { TLDRBlock } from './TLDRBlock'
import { MarketPulse } from './MarketPulse'
import { ReviewDocument } from './ReviewDocument'
import { FeedbackButton, ThirdAnalysisUnlock } from './Feedback'
import { SkeletonLoader } from './SkeletonLoader'

function Card({ children, delay = 0, className = '' }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45, delay, ease: [0.22, 1, 0.36, 1] }}
      className={`roast-card ${className}`}
    >
      {children}
    </motion.div>
  )
}

function SectionLabel({ children }) {
  return <div className="section-label">{children}</div>
}

function PercentileBar({ range, confidence }) {
  const match = range?.match(/(\d+)(?:th|st|nd|rd)[–\-](\d+)/)
  const single = range?.match(/(\d+)(?:th|st|nd|rd)\s*percentile/)
  let pct = 50
  if (match) pct = (parseInt(match[1]) + parseInt(match[2])) / 2
  else if (single) pct = parseInt(single[1])

  const numericMatch = range?.match(/^([\d\w\-–]+(?:th|st|nd|rd))/)
  const numericPart = numericMatch ? numericMatch[0] : range
  const labelPart = numericMatch ? range?.slice(numericPart.length) : ''

  const confidenceLabel = confidence === 'calibrated'
    ? 'Based on real applicant data'
    : 'Estimated from market signals'

  return (
    <div className="space-y-3">
      <div className="text-3xl sm:text-4xl font-bold tracking-tight">
        <span className="text-orange-400">{numericPart}</span>
        {labelPart && <span className="text-[--roast-text] text-xl font-medium">{labelPart}</span>}
      </div>
      <div className="percentile-bar">
        <motion.div
          className="percentile-bar-fill"
          initial={{ width: 0 }}
          animate={{ width: `${pct}%` }}
          transition={{ duration: 1.2, delay: 0.4, ease: [0.22, 1, 0.36, 1] }}
        />
      </div>
      <p className="text-xs text-[--roast-muted]">{confidenceLabel}</p>
    </div>
  )
}

function CopyAllButton({ review, competitive, marketContext }) {
  const [copied, setCopied] = useState(false)

  const copyAll = () => {
    if (!review) return
    const lines = [
      '🔥 ROAST RESULTS',
      '═'.repeat(50),
      '',
      'BOTTOM LINE',
      `Shortlist chance: ${review.tldr_shortlist_chance}`,
      `Biggest blocker: ${review.tldr_biggest_blocker}`,
      `Fix first: ${review.tldr_fix_first}`,
      '',
      competitive ? `WHERE YOU STAND\n${competitive.percentile_estimate?.range}` : '',
      '',
      "WHAT'S WORKING",
      review.whats_working_section,
      '',
      "WHAT'S HURTING YOU",
      review.whats_hurting_section,
      '',
      'CAREER STORY',
      review.career_story_section,
      '',
      'COMPETITIVE POSITION',
      review.competitive_position_section,
      '',
      'ACTION PLAN',
      review.action_plan_section,
      review.jd_alignment_section ? `\nJD ALIGNMENT\n${review.jd_alignment_section}` : '',
      '',
      '─'.repeat(50),
      'Generated by ROAST — roast.dev',
    ].filter(Boolean).join('\n')

    navigator.clipboard.writeText(lines)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  return (
    <button onClick={copyAll} className={`copy-btn ${copied ? 'copied' : ''}`}>
      {copied ? <Check size={12} /> : <Copy size={12} />}
      {copied ? 'Copied!' : 'Copy full roast'}
    </button>
  )
}

export function ResultsPage({ sections, sessionId, meta, analysisCount }) {
  const review = sections.review
  const marketContext = sections.market_context
  const competitive = sections.competitive

  return (
    <div className="min-h-screen px-4 py-8 sm:py-12 relative z-10">
      <div className="max-w-2xl mx-auto space-y-5">

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="flex items-start justify-between gap-4 px-1"
        >
          <div className="space-y-1 min-w-0">
            <p className="text-xs text-[--roast-muted] uppercase tracking-widest font-mono truncate">
              {meta.role} · {meta.companyType} · {meta.market}
            </p>
            <h1 className="text-2xl sm:text-3xl font-bold">Your Roast</h1>
          </div>
          {review && (
            <div className="shrink-0 pt-1">
              <CopyAllButton review={review} competitive={competitive} marketContext={marketContext} />
            </div>
          )}
        </motion.div>

        {/* TL;DR */}
        <Card delay={0.05}>
          {review ? (
            <TLDRBlock review={review} />
          ) : (
            <SkeletonLoader lines={4} />
          )}
        </Card>

        {/* Market Pulse */}
        <Card delay={0.1}>
          <MarketPulse marketContext={marketContext} fullContext={sections.market_intel || null} loading={!marketContext} />
        </Card>

        {/* The Review */}
        <Card delay={0.15}>
          <ReviewDocument review={review} sessionId={sessionId} loading={!review} />
        </Card>

        {/* Where You Stand */}
        {competitive && (
          <Card delay={0.2}>
            <SectionLabel>
              <TrendingUp size={11} />
              Where You Stand
            </SectionLabel>
            <PercentileBar
              range={competitive.percentile_estimate?.range}
              confidence={competitive.percentile_estimate?.confidence}
            />

            {/* CTC Range */}
            {competitive.expected_ctc_range && (
              <div className="mt-4 px-4 py-3 rounded-xl bg-orange-500/6 border border-orange-500/15">
                <p className="text-xs text-[--roast-muted] mb-0.5">Expected offer range</p>
                <p className="text-base font-semibold text-orange-300 font-mono">{competitive.expected_ctc_range}</p>
              </div>
            )}

            <div className="h-px bg-[--roast-border] my-4" />

            {/* Strengths vs pool */}
            {competitive.strengths_vs_pool?.length > 0 && (
              <div className="space-y-2 mb-4">
                <p className="text-xs text-[--roast-muted] uppercase tracking-wider">Edges over the pool</p>
                <ul className="space-y-1.5">
                  {competitive.strengths_vs_pool.map((s, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-[--roast-text-2]">
                      <span className="text-emerald-400 mt-0.5 shrink-0">+</span>
                      {s}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Weaknesses vs pool */}
            {competitive.weaknesses_vs_pool?.length > 0 && (
              <div className="space-y-2 mb-4">
                <p className="text-xs text-[--roast-muted] uppercase tracking-wider">Where you fall behind</p>
                <ul className="space-y-1.5">
                  {competitive.weaknesses_vs_pool.map((w, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-[--roast-text-2]">
                      <span className="text-red-400 mt-0.5 shrink-0">−</span>
                      {w}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            <div className="h-px bg-[--roast-border] my-4" />
            <p className="text-sm text-[--roast-text-2] leading-relaxed">{competitive.highest_leverage_change}</p>
          </Card>
        )}

        {analysisCount >= 2 && <ThirdAnalysisUnlock />}

        {review && (
          <FeedbackButton
            sessionId={sessionId}
            role={meta.role}
            market={meta.market}
            companyType={meta.companyType}
          />
        )}

      </div>
    </div>
  )
}
